image:
  file: .gitpod.Dockerfile
tasks:
  - name: rstudio
    # env:
      # R_LIBS_USER: /home/gitpod/libs
    command: /usr/lib/rstudio-server/bin/rstudio-server start
ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore    